import React from "react";

const projects = [
  {
    title: "Indian States Game",
    categories: ["Frontend"],
    status: null,
    learned: "Built interactive UI with Python, Tkinter, and JS logic to manage score and highlight missing states.",
    role: "Solo Project",
    image: "",
    github: "https://github.com/samarth96k/Indian-States-Game",
    live: "https://samarth96k.github.io/Indian-States-Game/",
    tech: ["Python", "HTML", "CSS", "JavaScript", "Tkinter"],
    desc: "An interactive learning game that helps students learn Indian states, with score tracking and a final summary highlighting unguessed states in red.",
    date: "2023",
  },
  {
    title: "Driver Drowsiness Detection System",
    categories: ["Machine Learning", "Computer Vision"],
    status: null,
    learned: "Implemented real-time detection using OpenCV, YOLO, Vision Transformer, and integrated Google Health API for heartbeat analysis.",
    role: "Team Project",
    image: "/images/driver-drowsiness.png",
    github: "https://github.com/samarth96k/Driver_Drowsiness_Detection",
    live: null,
    tech: ["Python", "Machine Learning", "OpenCV", "YOLO", "Vision Transformer"],
    desc: "A real-time driver drowsiness detection system using computer vision, ML models, and Google Health API data to analyze eye closure, yawning, and heart-rate patterns. Achieves ~92% accuracy and triggers alarms and emergency alerts during prolonged drowsiness.",
    date: "2023",
  },
  {
    title: "Portfolio Website",
    categories: ["React", "Frontend"],
    status: null,
    learned: "Built a responsive portfolio using React, improving component-based design and CSS styling skills.",
    role: "Solo Project",
    image: "/images/portfolio.png",
    github: "https://github.com/samarth96k/portfolio",
    live: "https://samarth96k.github.io/portfolio",
    tech: ["React", "JavaScript", "CSS"],
    desc: "A modern, responsive personal portfolio showcasing my projects, skills, and experience, built with React for smooth UI interactions.",
    date: "2024",
  },
  {
    title: "Drum App",
    categories: ["Frontend"],
    status: null,
    learned: "Practiced JS event listeners and DOM manipulation to create interactive audio-based UI.",
    role: "Solo Project",
    image: "/images/drum-app.png",
    github: "https://github.com/samarth96k/Drum-Game",
    live: "https://samarth96k.github.io/Drum-Game/",
    tech: ["HTML", "CSS", "JavaScript"],
    desc: "A simple yet impactful frontend project that simulates a virtual drum kit using clicks and keyboard events. Built to practice JS fundamentals like event listeners and DOM interactions, and boosted my confidence in frontend development.",
    date: "2023",
  },
  {
    title: "CGPA Calculator App",
    categories: ["JavaScript", "Frontend"],
    status: null,
    learned: "Handled edge cases like missing grades/credits while computing results, improving logic and DOM manipulation skills.",
    role: "Solo Project",
    image: "/images/cgpa-calculator.png",
    github: "https://github.com/samarth96k/cgpa-calc-test",
    live: "https://samarth96k.github.io/cgpa-calc-test/",
    tech: ["HTML", "CSS", "JavaScript"],
    desc: "A browser-based CGPA calculator that handles edge cases like missing grades or credits while computing results accurately. Built with clean JS logic to ensure seamless validation and error handling.",
    date: "2025",
  },
  {
    title: "Blog Project",
    categories: ["Full Stack", "JavaScript"],
    status: null,
    learned: "Implemented dynamic views with Node.js, Express, and EJS. Learned modal-based UI and prepared for multi-user authentication.",
    role: "Solo Project",
    image: "/images/blog-project.png",
    github: "https://github.com/samarth96k/Blog-Project",
    live: null,
    tech: ["HTML", "CSS", "JavaScript", "Node.js", "Express", "EJS"],
    desc: "A full-stack blogging platform built with Node.js, Express, and EJS, featuring dynamic views and a modal-based interface for creating new posts. Designed to refine backend fundamentals and frontend skills, with upcoming support for multi-user authentication.",
    date: "2025",
    status:""
  },
];

export default projects;